---
title: "Data Preprocessing for Predictive Maintenance Dataset"
author: "Avinash"
date: '2018-07-17'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Importing dependencies
library(tidyverse)
library(purrr)
library(lubridate)
```

# Preprocessing for task 1

```{r}
clf_data <- read_csv("../data/predictive_maintenance_dataset.csv")
```


```{r}
clf_data %>% filter(unit_number == 540) %>%
  arrange(time_stamp) %>%
  mutate(new_status = lead(status,40)) %>% 
  mutate(new_status = ifelse(is.na(new_status), 1, new_status)) %>% 
  select(-c(status)) %>%
  rename(status = new_status)
```


```{r}
process_data <- function(unit_id) {
  #Set the target variable to 40 days ahead
  #Removes the data after that
  ret_data <- clf_data %>%
    filter(unit_number == unit_id) %>%
    arrange(time_stamp) %>%
    mutate(new_status = lead(status,40)) %>%
    mutate(new_status = ifelse(is.na(new_status), 1, new_status)) %>% 
    select(-c(status)) %>%
    rename(status = new_status)
  
  return(ret_data)
}
```

```{r}
#Update the target variable for all the generator units!
updated_data <- select(clf_data, unit_number)[[1]] %>% unique() %>% map_dfr(.f = process_data)
```

```{r}
#Checking if the number of rows have reduced
nrow(clf_data)
nrow(updated_data)
```


```{r}
#Checking if there are 41 records 
updated_data %>% group_by(unit_number, status) %>% summarise(count = n())
```


```{r}
#Checking if the output is in the required format
updated_data %>%
  filter(unit_number == 540) %>%
  arrange(time_stamp)
  
clf_data %>% filter(unit_number == 540) %>%
  arrange(time_stamp) %>%
  mutate(new_status = lead(status,40)) %>% 
  mutate(new_status = ifelse(is.na(new_status), 1, new_status)) %>% 
  select(-c(status)) %>%
  rename(status = new_status)
```


```{r}
write_csv(updated_data, "../results/processed_data/predictive_maintenance_dataset_processed.csv")
```